require:
  - rubocop-rails
  - rubocop-i18n
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety
  - rubocop-minitest

AllCops:
  NewCops: enable

I18n/GetText/DecorateString:
  Enabled: false
  Exclude:
    - spec/**/*.rb

I18n/RailsI18n/DecorateString:
  Enabled: false
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/NotNullColumn:
  Exclude:
    - 'db/migrate/*' 

I18n/GetText/DecorateFunctionMessage:
  Exclude:
    - 'app/controllers/concerns/authentication.rb'
  Enabled: false