require:
  - rubocop-rails
  - rubocop-i18n
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety
  - rubocop-minitest

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - tmp/**/*
    - app/controllers/graphql_controller.rb
    - app/graphql/task_tracker_itis_schema.rb
    - app/graphql/types/mutation_type.rb

I18n/GetText/DecorateString:
  Enabled: false
  Exclude:
    - spec/**/*.rb

I18n/RailsI18n/DecorateString:
  Enabled: false
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/NotNullColumn:
  Exclude:
    - 'db/migrate/*' 

I18n/GetText/DecorateFunctionMessage:
  Exclude:
    - 'app/controllers/concerns/authentication.rb'
  Enabled: false

Metrics/MethodLength:
  Max: 20